#page title
page_title: Market Mela - India's No.1 Budget Fashion Store # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1576741080 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: in # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://apps.apple.com/in/app/market-mela/id1576741080 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=com.marketmela.app # Enter Google Play Store URL.
presskit_download_link:
  https://www.instagram.com/marketmela.in/ # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/mm_logo.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Market Mela # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: India's No.1 Budget Faishon Store

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Team Market Mela
your_link: https://www.instagram.com/marketmela.in/
your_city: India
email_address: admin@marketmela.in
facebook_username: marketmela.in
instagram_username: marketmela.in
twitter_username: marketmela.in
github_username: scorchy38
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Unique and Magical Collections
    description: Drops you cannot resist! Explore and buy from India's best fashion collection, a mixture of latest trends, sophisticated designs and cheerful colors.
    fontawesome_icon_name: magic

  - title: Smooth Ordering Process
    description: Our mobile app allows you to easily order products providing a seemless experience and tons of offers.
    fontawesome_icon_name: mobile

  - title: Live Order Tracking
    description: Track your order in real-time and experience the fastest delivery in every corner of the country.
    fontawesome_icon_name: play-circle

  - title: Exchange and Returns
    description: Exchanges and returns are considered when you receive the wrong product from our end, we provide full cooperation and assure a fast resolution process.
    fontawesome_icon_name: sync

  - title: Free Cash on Delivery
    description: Free Cash on Delivery on every order along with a huge variety of other payment options including UPI, Wallets and Cards.
    fontawesome_icon_name: adjust

  - title: Executive Support
    description: We provide 24x7 call/whatsapp support to our customers regarding any type of query.
    fontawesome_icon_name: star

  - title: #Smart App Banner
    description: #Display a smart app banner on iOS devices.
    fontawesome_icon_name: #arrow-alt-circle-down

  - title: #Social Links
    description: #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name: #link

  - title: #FontAwesome Support
    description: #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name: #info-circle

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#745C94"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

theme: jekyll-theme-cayman